"""
Procedure-quiz domain constants (סד"פ).

Enums for the procedure / question / attempt lifecycle plus the Telegram-side
limits the generation + poll code must respect (Telegram rejects overlong quiz
polls, so we enforce them server-side rather than letting the send fail).
"""

import enum

# Telegram quiz-poll hard limits. Questions/options over these are rejected by
# the API, so generation truncates and the admin editor validates against them.
MAX_QUESTION_CHARS = 300
MAX_OPTION_CHARS = 100
MIN_OPTIONS = 2
MAX_OPTIONS = 4

# A published procedure older than this (hours) becomes eligible for the
# one-time "you haven't done the quiz yet" reminder.
REMINDER_AGE_HOURS = 48


class ProcedureStatus(str, enum.Enum):
    """Lifecycle of a security procedure (סד"פ)."""

    DRAFT = "draft"          # created, questions being generated/edited
    PUBLISHED = "published"  # broadcast to guards, quiz live
    ARCHIVED = "archived"    # retired from the menu (history stays)


class QuestionSource(str, enum.Enum):
    """How a quiz question originated.

    AI — generated by Claude; may be auto-deleted on regeneration only while
    still unedited. MANUAL — added by the admin; always survives regeneration.
    """

    AI = "ai"
    MANUAL = "manual"


class AttemptStatus(str, enum.Enum):
    """Lifecycle of a single guard's quiz attempt."""

    IN_PROGRESS = "in_progress"  # started, not all questions answered yet
    FINISHED = "finished"        # every sampled question answered + scored
    ABANDONED = "abandoned"      # superseded by a newer attempt / never resumed
