"""add actual schedule layer tables

Revision ID: 08da952dbb11
Revises: b7d9f1a3c5e8
Create Date: 2026-07-05 19:05:21.422945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08da952dbb11'
down_revision: Union[str, Sequence[str], None] = 'b7d9f1a3c5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actual_schedules',
    sa.Column('week_id', sa.Uuid(), nullable=False),
    sa.Column('seeded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_source', sa.String(length=20), server_default='lazy', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['schedule_weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actual_schedules_week_id'), 'actual_schedules', ['week_id'], unique=True)
    op.create_table('actual_positions',
    sa.Column('actual_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('day_schedules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('required_attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_event', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('event_required_count', sa.Integer(), nullable=True),
    sa.Column('source_position_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actual_schedule_id'], ['actual_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actual_positions_actual_schedule_id'), 'actual_positions', ['actual_schedule_id'], unique=False)
    op.create_table('actual_assignments',
    sa.Column('actual_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('actual_position_id', sa.Uuid(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('segment_start', sa.String(length=5), nullable=True),
    sa.Column('segment_end', sa.String(length=5), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actual_position_id'], ['actual_positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['actual_schedule_id'], ['actual_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actual_position_id', 'day_index', 'user_id', name='uq_actual_assignment_cell_user')
    )
    op.create_index(op.f('ix_actual_assignments_actual_position_id'), 'actual_assignments', ['actual_position_id'], unique=False)
    op.create_index(op.f('ix_actual_assignments_actual_schedule_id'), 'actual_assignments', ['actual_schedule_id'], unique=False)
    op.create_index(op.f('ix_actual_assignments_user_id'), 'actual_assignments', ['user_id'], unique=False)
    # (autogenerate also proposed dropping the orphan dev-only 'schedule_events'
    # table and JSON→JSONB no-op alters on attendance_adjustments — unrelated
    # drift, pruned from this migration on purpose.)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actual_assignments_user_id'), table_name='actual_assignments')
    op.drop_index(op.f('ix_actual_assignments_actual_schedule_id'), table_name='actual_assignments')
    op.drop_index(op.f('ix_actual_assignments_actual_position_id'), table_name='actual_assignments')
    op.drop_table('actual_assignments')
    op.drop_index(op.f('ix_actual_positions_actual_schedule_id'), table_name='actual_positions')
    op.drop_table('actual_positions')
    op.drop_index(op.f('ix_actual_schedules_week_id'), table_name='actual_schedules')
    op.drop_table('actual_schedules')
    # ### end Alembic commands ###
