"""add supervisor_name to actual_reinforcements

Revision ID: 7b3c0c23e716
Revises: 955d5da3c61e
Create Date: 2026-07-05 20:20:52.925722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b3c0c23e716'
down_revision: Union[str, Sequence[str], None] = '955d5da3c61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actual_reinforcements', sa.Column('supervisor_name', sa.String(length=100), nullable=True))
    # (usual autogenerate noise pruned: schedule_events drop + JSON alters.)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actual_reinforcements', 'supervisor_name')
    # ### end Alembic commands ###
