"""add reinforcement guards (is_reinforcement + actual_reinforcements)

Revision ID: 955d5da3c61e
Revises: 08da952dbb11
Create Date: 2026-07-05 20:09:23.308713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '955d5da3c61e'
down_revision: Union[str, Sequence[str], None] = '08da952dbb11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actual_reinforcements',
    sa.Column('actual_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actual_schedule_id'], ['actual_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actual_schedule_id', 'user_id', name='uq_actual_reinforcement_week_user')
    )
    op.create_index(op.f('ix_actual_reinforcements_actual_schedule_id'), 'actual_reinforcements', ['actual_schedule_id'], unique=False)
    op.create_index(op.f('ix_actual_reinforcements_user_id'), 'actual_reinforcements', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_reinforcement', sa.Boolean(), server_default='0', nullable=False))
    # (autogenerate noise pruned again: orphan dev-only 'schedule_events' drop
    # + JSON→JSONB no-op alters on attendance_adjustments.)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_reinforcement')
    op.drop_index(op.f('ix_actual_reinforcements_user_id'), table_name='actual_reinforcements')
    op.drop_index(op.f('ix_actual_reinforcements_actual_schedule_id'), table_name='actual_reinforcements')
    op.drop_table('actual_reinforcements')
    # ### end Alembic commands ###
