"""add requirement attributes

Revision ID: 95be7724eba5
Revises: aae292ee0218
Create Date: 2026-06-16 21:10:22.479179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95be7724eba5'
down_revision: Union[str, Sequence[str], None] = 'aae292ee0218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_attributes',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_attributes_key'), 'requirement_attributes', ['key'], unique=True)
    # NOTE: autogenerate also flagged op.drop_table('schedule_events') — pre-existing
    # DB drift (legacy table with no model), out of scope. Removed.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_requirement_attributes_key'), table_name='requirement_attributes')
    op.drop_table('requirement_attributes')
