"""add week_profile_assignments (week<->profile binding)

Revision ID: 997d74570060
Revises: f1a2b3c4d5e6
Create Date: 2026-06-28 20:31:30.456965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '997d74570060'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('week_profile_assignments',
    sa.Column('week_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['activation_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['schedule_weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_week_profile_assignments_profile_id'), 'week_profile_assignments', ['profile_id'], unique=False)
    op.create_index(op.f('ix_week_profile_assignments_week_id'), 'week_profile_assignments', ['week_id'], unique=True)
    # NOTE: autogenerate also flagged a drop of the unrelated, pre-existing
    # 'schedule_events' table (DB drift with no model). Intentionally NOT
    # touched here — out of scope for part B.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_week_profile_assignments_week_id'), table_name='week_profile_assignments')
    op.drop_index(op.f('ix_week_profile_assignments_profile_id'), table_name='week_profile_assignments')
    op.drop_table('week_profile_assignments')
    # ### end Alembic commands ###
