"""
QuizQuestion model — one MCQ in a procedure's bank.

Generated by Claude (source=AI) or added by the admin (source=MANUAL). After
publish, questions can be disabled (is_active=False) instead of deleted, so an
attempt's history stays valid by reference. ``edited_at`` is set on any admin
edit; regeneration may delete ONLY ``source=AI AND edited_at IS NULL`` rows, so
admin refinements and manual questions always survive a re-generate.
"""

from datetime import datetime
from typing import TYPE_CHECKING
import uuid

from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import BaseModel
from app.procedures.constants import QuestionSource

if TYPE_CHECKING:
    from app.procedures.models.procedure import Procedure

# JSON list of 2–4 option strings. Declared as Text-backed JSON to keep SQLite
# (tests) and PostgreSQL (prod) identical without a dialect import here.
from sqlalchemy import JSON
from sqlalchemy.dialects.postgresql import JSONB

JSONType = JSON().with_variant(JSONB(), "postgresql")


class QuizQuestion(BaseModel):
    """One multiple-choice question in a procedure's quiz bank."""

    procedure_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("procedures.id", ondelete="CASCADE"), nullable=False
    )

    text: Mapped[str] = mapped_column(Text, nullable=False)
    options: Mapped[list] = mapped_column(JSONType, nullable=False)
    correct_index: Mapped[int] = mapped_column(Integer, nullable=False)
    display_order: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Admin can disable (instead of delete) a question after publish so history
    # by reference stays valid. Disabled questions are excluded from sampling.
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default="1"
    )

    source: Mapped[QuestionSource] = mapped_column(
        Enum(QuestionSource, name="question_source"),
        nullable=False,
        default=QuestionSource.AI,
    )
    # Set on any admin edit; protects the row from regeneration deletion.
    edited_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    procedure: Mapped["Procedure"] = relationship(back_populates="questions")
